---
- name: Restart Patroni Service
  ansible.builtin.systemd_service:
    name: patroni
    state: restarted

- name: Restart Etcd Service
  ansible.builtin.systemd_service:
    name: etcd
    state: restarted
...
