---
- name: Setup patroni
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - vars/{{ inventory_hostname }}.yml
    - vars/sandbox.yml

  tasks:
    - name: Include pg_setup_patroni role
      ansible.builtin.include_role:
        name: pg_setup_patroni
...
