---
- name: Create etcd group
  ansible.builtin.group:
    name: etcd
    state: present

- name: Create etcd service account
  ansible.builtin.user:
    name: etcd
    state: present
    groups:
      - etcd
    shell: /sbin/nologin
    home: /opt/etcd
    system: true
    createhome: true
...
